server:
  port: 8080

eureka:
  client:
    serviceUrl:
      # ✅ USAR VARIABLE DE ENTORNO
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service-route
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/transactions/**
