server:
  port: 8080

eureka:
  client:
    serviceUrl:
      # TRUCO PRO: Si existe la variable EUREKA_URI usa eso, si no, usa localhost (para tu IDE)
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Aquí definimos las rutas explícitas
        - id: account-service-route
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/transactions/**
