server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/myfinances-realm/protocol/openid-connect/certs

management:
  tracing:
    sampling:
      probability: 1.0

zipkin:
  tracing:
    endpoint: http://zipkin:9411/api/v2/spans
