spring.application.name=goals-service
server.port=8085

# --- Base de Datos ---
spring.datasource.url=jdbc:postgresql://postgres-db:5432/goals_db
spring.datasource.username=myfinances_user
spring.datasource.password=myfinances_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# --- Services URLs ---
services.account-service.url=http://account-service:8081

# --- Observabilidad ---
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# --- Feign ---
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

# --- Circuit Breaker ---
resilience4j.circuitbreaker.instances.accountServiceBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.accountServiceBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.accountServiceBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.accountServiceBreaker.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.accountServiceBreaker.failureRateThreshold=50
